// Axios
export const IS_LOADING = "IS_LOADING";
export const NETWORK_RESPONSE = "NETWORK_RESPONSE";
export const NETWORK_ERROR = "NETWORK_ERROR";
export const TIMER_START = "TIMER_START";
export const TIMER_END = "TIMER_END";

// User
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const SERVER_ERROR = "SERVER_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const LOGOUT = "LOGOUT";

// Poems & Submissions
export const NEW_SUBMISSION_SUCCESS = "NEW_SUBMISSION_SUCCESS";
export const SET_MAIN_SEARCH_QUERY = "SET_MAIN_SEARCH_QUERY";
export const CLEAR_MAIN_SEARCH_QUERY = "CLEAR_MAIN_SEARCH_QUERY";
export const SET_LAZY_LOADING_LIST_STATE = "SET_LAZY_LOADING_LIST_STATE";
export const QUERY_ADDITIONAL_SUBMISSION_NO_RESULT =
	"QUERY_ADDITIONAL_SUBMISSION_NO_RESULT";
export const QUERY_ADDITIONAL_SUBMISSIONS_RESULT =
	"QUERY_ADDITIONAL_SUBMISSIONS_RESULT";
export const NEW_SUBMISSION_FAIL = "NEW_SUBMISSION_FAIL";
export const REMOVE_SUBMISSION_SUCCESS = "REMOVE_SUBMISSION_SUCCESS";
export const GET_POSTS_LAZILY_LOADING = "GET_POSTS_LAZILY_LOADING";
export const SET_FEATURED_POSTS = "SET_FEATURED_POSTS";
export const QUERY_OWN_SUBMISSION_RESULT = "QUERY_OWN_SUBMISSION_RESULT";
export const CLEAR_OWN_QUERY_RESULTS = "CLEAR_OWN_QUERY_RESULTS";
export const QUERY_ALL_SUBMISSION_RESULTS = "QUERY_ALL_SUBMISSION_RESULTS";
export const CLEAR_ALL_QUERY_RESULTS = "CLEAR_ALL_QUERY_RESULTS";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const SET_CURRENTLY_EDITING_POST = "SET_CURRENTLY_EDITING_POST";
export const SET_SEARCH_OWN_POSTS_SEARCH_INPUT =
	"SET_SEARCH_OWN_POSTS_SEARCH_INPUT";
export const CLEAR_CURRENTLY_EDITING_POST = "CLEAR_CURRENTLY_EDITING_POST";
export const RESET_SEARCH_OWN_POSTS_SEARCH_INPUT =
	"RESET_SEARCH_OWN_POSTS_SEARCH_INPUT";
export const QUERY_OWN_SUBMISSION_NO_RESULT = "QUERY_OWN_SUBMISSION_NO_RESULT";
export const GET_BY_TAG_SUCCESS = "GET_BY_TAG_SUCCESS";
export const QUERY_ALL_SUBMISSION_NO_RESULT = "QUERY_ALL_SUBMISSION_NO_RESULT";
export const SUBMIT_CURRENTLY_EDITING_POST_SUCCESS =
	"SUBMIT_CURRENTLY_EDITING_POST_SUCCESS";

// Forms
export const RESET_SUBMISSION_FORM = "RESET_SUBMISSION_FORM";
export const SET_SUBMISSION_FORM = "SET_SUBMISSION_FORM";
export const SET_NEW_TAG_SUBMISSION_FORM = "SET_NEW_TAG_SUBMISSION_FORM";
export const REMOVE_TAG = "REMOVE_TAG";

// UI Stuff
export const SET_VIEWPORT_DIMS = "SET_VIEWPORT_DIMS";
export const SET_NAVBAR_HIDDEN = "SET_NAVBAR_HIDDEN";
export const RESET_NAVBAR_HIDDEN = "RESET_NAVBAR_HIDDEN";
export const SET_LARGE_MODAL_DATA = "SET_LARGE_MODAL_DATA";
export const RESET_LARGE_MODAL_DATA = "RESET_LARGE_MODAL_DATA";
export const SHOW_TOAST_NOTIFICATION = "SHOW_TOAST_NOTIFICATION";
export const RESET_TOAST_NOTIFICATION = "RESET_TOAST_NOTIFICATION";
export const SET_SNACKBAR_DATA = "SET_SNACKBAR_DATA";
export const RESET_SNACKBAR = "RESET_SNACKBAR";
export const SET_DRAWER_OPEN = "SET_DRAWER_OPEN";
export const SET_DRAWER_CLOSED = "SET_DRAWER_CLOSED";
export const SET_ANIMATE_SEARCH_RESULT = "SET_ANIMATE_SEARCH_RESULT";
