// Axios
export const IS_LOADING = "IS_LOADING";
export const NETWORK_RESPONSE = "NETWORK_RESPONSE";
export const NETWORK_ERROR = "NETWORK_ERROR";
export const TIMER_START = "TIMER_START";
export const TIMER_END = "TIMER_END";

// User
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const SERVER_ERROR = "SERVER_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const LOGOUT = "LOGOUT";

// Poems & Submissions
export const NEW_SUBMISSION_SUCCESS = "NEW_SUBMISSION_SUCCESS";
export const NEW_SUBMISSION_FAIL = "NEW_SUBMISSION_FAIL";
export const REMOVE_SUBMISSION_SUCCESS = "REMOVE_SUBMISSION_SUCCESS";
export const QUERY_OWN_SUBMISSION_RESULT = "QUERY_OWN_SUBMISSION_RESULT";
export const CLEAR_OWN_QUERY_RESULTS = "CLEAR_OWN_QUERY_RESULTS";
export const QUERY_ALL_SUBMISSION_RESULTS = "QUERY_ALL_SUBMISSION_RESULTS";
export const CLEAR_ALL_QUERY_RESULTS = "CLEAR_ALL_QUERY_RESULTS";
export const SET_CURRENTLY_EDITING_POST = "SET_CURRENTLY_EDITING_POST";
export const CLEAR_CURRENTLY_EDITING_POST = "CLEAR_CURRENTLY_EDITING_POST";
export const SUBMIT_CURRENTLY_EDITING_POST_SUCCESS =
	"SUBMIT_CURRENTLY_EDITING_POST_SUCCESS";

// Forms
export const RESET_SUBMISSION_FORM = "RESET_SUBMISSION_FORM";
export const SET_SUBMISSION_FORM = "SET_SUBMISSION_FORM";

// UI Stuff
export const SET_NAVBAR_HIDDEN = "SET_NAVBAR_HIDDEN";
export const RESET_NAVBAR_HIDDEN = "RESET_NAVBAR_HIDDEN";
export const SET_LARGE_MODAL_DATA = "SET_LARGE_MODAL_DATA";
export const RESET_LARGE_MODAL_DATA = "RESET_LARGE_MODAL_DATA";
