// Axios
export const IS_LOADING = "IS_LOADING";
export const NETWORK_RESPONSE = "NETWORK_RESPONSE";
export const NETWORK_ERROR = "NETWORK_ERROR";
export const TIMER_START = "TIMER_START";
export const TIMER_END = "TIMER_END";

// User
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const UNAUTHORIZED = "UNAUTHORIZED";
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const SERVER_ERROR = "SERVER_ERROR";
export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS";
export const LOGOUT = "LOGOUT";

// Poems & Submissions
export const NEW_SUBMISSION_SUCCESS = "NEW_SUBMISSION_SUCCESS";
export const NEW_SUBMISSION_FAIL = "NEW_SUBMISSION_FAIL";
export const REMOVE_SUBMISSION_SUCCESS = "REMOVE_SUBMISSION_SUCCESS";
