import React, { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeroSection from "../components/landing/HeroSection";
import { autoLoginOnFirstRequest } from "../util/autoLogin";
import Cookies from "cookies";
import mongoose from "mongoose";
import Submission from "../models/Submission";
import LandingBottomSection from "../components/landing/LandingBottomSection";
import { connect } from "react-redux";
import clsx from "clsx";

const Home = ({
	latestSubmissions,
	posts: {
		hasSearchResults,
		filteredAllPosts: { noResult, byTag, byBody },
	},
}) => {
	const [poemCardArray, setPoemCardArray] = useState([]);
	const [hideOverflow, setHideOverflow] = useState(false);
	useEffect(() => {
		if (hasSearchResults) {
			setHideOverflow(false);
		} else {
			setHideOverflow(false);
		}
	}, [hasSearchResults, noResult, byTag, byBody]);

	useEffect(() => {
		if (latestSubmissions.length > 0 && !hasSearchResults) {
			setPoemCardArray(latestSubmissions.slice(0, 3));
		}
	}, [hasSearchResults, noResult, byTag, byBody]);
	console.log("hasSearchResults: ", hasSearchResults);

	console.log("styles.overflowVisible: ", styles.overflowVisible);
	return (
		<div
			className={clsx(
				styles.container,
				hasSearchResults && styles.overflowVisible
			)}
			id="index-container"
		>
			<Head>
				<title>Poetry Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeroSection poemCardArray={poemCardArray} />
			<LandingBottomSection poemCardArray={poemCardArray} />
		</div>
	);
};

const mapStateToProps = (state, props) => ({
	posts: state.posts,
	props: props,
});

export default connect(mapStateToProps)(Home);

export const getServerSideProps = async (ctx) => {
	// let _user = await autoLoginOnFirstRequest(ctx.req, ctx.res);
	let latestSubmissions = await mongoose
		.connect(process.env.MONGO_URI, {
			useNewUrlParser: true,
			useUnifiedTopology: true,
		})
		.then(async () => {
			let r = await Submission.find()
				.sort({ createdAt: -1 })
				.limit(10)
				.populate({
					path: "author",
					select: "firstName lastName email _id",
				});
			return r;
		});
	return {
		props: {
			// hasUser: _user,
			latestSubmissions: JSON.parse(JSON.stringify(latestSubmissions)),
		},
	};
};
