import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import HeroSection from "../components/landing/HeroSection";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Poetry Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<HeroSection />
			<footer className={styles.footer}>
				<a
					href="https://www.igloodevelopment.dev/"
					target="_blank"
					rel="noopener noreferrer"
				>
					By Andrew Mueller
				</a>
			</footer>
		</div>
	);
}
